### PR TITLE
Attempt to expose io::Cursor

### PR DESCRIPTION
**Pull request by whitequark**
This is as far as I got. The 2nd commit is rejected by patch for some reason that elides me.

### CODE REVIEW

**Comment by whitequark** [comment]
Are you willing to finish this on contractual basis?

**Comment by jethrogb** [comment]
> The 2nd commit is rejected by patch for some reason that elides me.

Are you editing the patches by hand?

**Comment by jethrogb** [comment]
So your patch doesn't actually work, because the implementation for `Read` uses `BufRead::fill_buf` which requires collections...

**Comment by jethrogb** [comment]
Resolved in master, closing this.

**Comment by whitequark** [comment]
Thanks a lot!

**Pull request closed without merging**
