### PR TITLE
Update to 2019-04-27

### PR DESCRIPTION
**Pull request by parasyte**
This supersedes #16 and is based on #17

### CODE REVIEW

**Comment by jethrogb** [comment]
Beats me how you were able to generate this with this issue: https://github.com/jethrogb/rust-core_io/pull/17#discussion_r279207441 but this LGTM! Thanks a lot!

**Comment by jethrogb** [comment]
Why does vectored I/O require `feature="collections"`?

**Comment by jethrogb** [comment]
Same question for `TryInto`

**Comment by parasyte** [comment]
Oh, these don’t need the collections feature. I was a little trigger happy. I’ll update the patches.

**Comment by jethrogb** [comment]
Sorry, I had to yank this because it failed to build on many versions. I've setup CI in https://github.com/jethrogb/rust-core_io/pull/21

**Comment by nicholastmosher** [comment]
Hey there, I'm trying to get this version to build, but it's saying it can't find `mod io;`

image

One thing that strikes me as odd about this is that there's no `src/271eb8fc5a420280937bb1745f1e7aee7901ad26` directory in my project structure. Isn't this supposed to be created by `build.rs` by applying the patch or something?

**Comment by jethrogb** [comment]
It looks like you might be working in a git clone of this project? Then you need to run `build-src.sh` first.

**Pull request merged**
