### PR TITLE
Updated to 2019-08-01

### PR DESCRIPTION
**Pull request by JCapucho**
Only one nightly build commit hash: `8a58268b5ad9c4a240be349a633069d48991eb0c`

### CODE REVIEW

**Comment by jethrogb** [comment]
There was more than one nightly between July 1 and August 1. This crate supports *all* nightlies up to the version number, so this PR isn't correct.

An easy way to get all the right commits is to use [rustc-commit-db](https://github.com/jethrogb/rustc-commit-db) as mentioned in the README. Please also update the version that CI uses to test.

**Comment by JCapucho** [comment]
I tried to pipe rustc-commit-db but it didnt give me any new commits after 9a90d03ad171856dc016c2dcc19292ec49a8a26f

**Comment by jethrogb** [comment]
You probably need to update the database first with the latest nightlies.

**Comment by JCapucho** [comment]
When i try to run the update subcommand it fails because it doesnt have aws s3 credentials and i dont know who to configure it

**Comment by MabezDev** [comment]
@JCapucho It seems it just needs to be given any form of credentials, try this:

```
AWS_ACCESS_KEY_ID="test" AWS_SECRET_ACCESS_KEY="test" ./commit-db.rb update --force
```

**Comment by JCapucho** [comment]
There is already a pull request for 2019-12-01 so i am going to close this

**Pull request closed without merging**
